# Generated by Django 5.1.4 on 2025-04-03 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('detail', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('modelname', models.CharField(max_length=300)),
                ('detail', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('image1', models.ImageField(upload_to='product_image')),
                ('image2', models.ImageField(upload_to='product_image')),
                ('image3', models.ImageField(upload_to='product_image')),
                ('image4', models.ImageField(upload_to='product_image')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.brand')),
            ],
        ),
    ]
