# Generated by Django 5.1.4 on 2025-04-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='order_item_images/'),
        ),
    ]
