# Generated by Django 5.1.4 on 2025-04-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0003_orderitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
